-- MySQL Script generated by MySQL Workbench
-- Tue Sep  3 09:37:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock` (
  `id_product` INT NOT NULL,
  `amount` INT NOT NULL,
  `stockcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `id_sales` INT NOT NULL,
  `id_product` INT NOT NULL,
  `sale_amount` INT NOT NULL,
  `salescol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_sales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_has_sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_has_sales` (
  `stock_id_product` INT NOT NULL,
  `sales_id_sales` INT NOT NULL,
  PRIMARY KEY (`stock_id_product`, `sales_id_sales`),
  INDEX `fk_stock_has_sales_sales1_idx` (`sales_id_sales` ASC) VISIBLE,
  INDEX `fk_stock_has_sales_stock_idx` (`stock_id_product` ASC) VISIBLE,
  CONSTRAINT `fk_stock_has_sales_stock`
    FOREIGN KEY (`stock_id_product`)
    REFERENCES `mydb`.`stock` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stock_has_sales_sales1`
    FOREIGN KEY (`sales_id_sales`)
    REFERENCES `mydb`.`sales` (`id_sales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
